services:
  ttforwarder:
    build: .
    env_file: .env
    restart: always
    healthcheck:
      test: ["CMD", "python", "healthcheck.py"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 10s
